### ISSUE TITLE
Grub2 on 486

### ISSUE THREAD

**Issue by baryluk** [yeokm1/gentoo-on-486#1]
Hi,

I noticed you expirienced issue with Grub2 on 486. Do you have some follow ups about this? Maybe opened a bug upstream about it? It could be some compiler / assembly issue, or maybe wrong compile flags, or maybe some issue with BIOS / IDE support?

**Comment by yeokm1** [comment]
Hi

Well I didn't have the time to debug and follow up this issue since this is just a hobby project. Besides, the priority of fixing such a bug will probably be very low. How many people will use a modern Linux\Grub2 with a 486?
